# Generated by Django 4.2.16 on 2024-11-18 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_customuser_options_customuser_foto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='departamento',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='semestre',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
