# Generated by Django 4.2.16 on 2024-11-22 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_customuser_departamento_alter_customuser_semestre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('codigo', models.CharField(max_length=50)),
                ('semestre', models.CharField(max_length=50)),
                ('curso', models.CharField(max_length=255)),
                ('tipo', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='customuser',
            name='foto',
            field=models.ImageField(blank=True, default='defaultphoto.jpg', null=True, upload_to='user_photos/'),
        ),
    ]
