# Generated by Django 4.2.16 on 2024-11-22 22:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_topico_postagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='disciplina',
            name='professor_responsavel',
            field=models.ForeignKey(blank=True, limit_choices_to={'user_type': 'professor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='disciplina',
            name='codigo',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='disciplina',
            name='semestre',
            field=models.CharField(max_length=10),
        ),
    ]
