# Generated by Django 4.2.16 on 2024-11-22 23:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_disciplina_professor_responsavel_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userdiscipline',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='userdiscipline',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='userdiscipline',
            name='added_at',
        ),
    ]
