# Generated by Django 4.2.16 on 2024-11-24 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_customuser_eventos_interesse_interesse'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_public_profile',
            field=models.BooleanField(default=True),
        ),
    ]
