# Generated by Django 4.2.16 on 2024-11-24 20:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_notificacao_disciplina_notificacao_evento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacao',
            name='disciplina',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notificacoes', to='core.disciplina'),
        ),
        migrations.AlterField(
            model_name='notificacao',
            name='evento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notificacoes', to='core.evento'),
        ),
    ]
