# Generated by Django 4.2.16 on 2024-11-28 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_notificacao_topico'),
    ]

    operations = [
        migrations.AddField(
            model_name='disciplina',
            name='turma',
            field=models.IntegerField(default=1),
        ),
    ]
