# Generated by Django 4.2.16 on 2024-12-01 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_horariograde'),
    ]

    operations = [
        migrations.CreateModel(
            name='Salas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_sala', models.CharField(max_length=255)),
                ('posição_x', models.FloatField()),
                ('posição_y', models.FloatField()),
            ],
        ),
    ]
