# Generated by Django 4.2.16 on 2024-12-01 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_predio_sala'),
    ]

    operations = [
        migrations.AddField(
            model_name='disciplina',
            name='sala',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disciplinas', to='core.sala'),
        ),
    ]
