# Generated by Django 4.2.16 on 2024-12-01 08:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_salas'),
    ]

    operations = [
        migrations.AddField(
            model_name='horariograde',
            name='Sala',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='horarios_grade', to='core.salas'),
        ),
    ]
