# Generated by Django 4.2.16 on 2024-12-01 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_disciplina_sala'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='evento',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='evento',
            name='local',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
