# Generated by Django 4.2.16 on 2024-12-04 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_evento_latitude_evento_longitude_alter_evento_local'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mapas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('planta', models.ImageField(upload_to='')),
                ('planta_2', models.ImageField(default=None, upload_to='')),
                ('predio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mapas', to='core.predio')),
            ],
        ),
    ]
