# Generated by Django 4.2.16 on 2024-12-04 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_mapas'),
    ]

    operations = [
        migrations.AddField(
            model_name='sala',
            name='pos_x',
            field=models.FloatField(default=400),
        ),
        migrations.AddField(
            model_name='sala',
            name='pos_y',
            field=models.FloatField(default=200),
        ),
    ]
