# Generated by Django 4.2.16 on 2024-12-01 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_mapas'),
    ]

    operations = [
        migrations.AddField(
            model_name='mapas',
            name='planta_2',
            field=models.ImageField(default=None, upload_to=''),
        ),
    ]
